### ISSUE TITLE
Simplify workflow

### ISSUE THREAD

**Issue by timherreijgers** [timherreijgers/Embedded-Device-Configurator#1]
The workflow can be generalized by adding the os to the matrix. Using the include entry we can specify which download link to use for each os, just like the compiler. This might look something like:

```yaml
    strategy:
      matrix:
        compiler_c: [gcc, clang]
        os: [ubuntu-latest, macos-10.15]
        include:
          - compiler_c: gcc
            compiler_cpp: g++
          - compiler_c: clang
            compiler_cpp: clang++
          - os: ubuntu-latest
            download_url: <url>
          - os: macos-10.15
            download_url: <url>
```
